name: CI

on:
  push:
    branches: [main]
    paths: &code
      - src/**
      - Cargo.toml
      - Cargo.lock
      - .github/workflows/ci.yml
  pull_request:
    paths: *code

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - run: cargo clippy --all-targets --locked -- -D warnings
      - run: cargo test --locked
